### ISSUE TITLE
limite mysql 

### ISSUE THREAD

**Issue by movvou** [RaspbianFrance/raspisms-deb-package#3]
Bonjour,

Désolé pour la méthode mais je ne maîtrise pas encore assez git pour apporter le correctif moi même.

La ligne 123 du fichier /var/www/html/RaspiSMS/createDatabase.sql fait planter l'installation sur une raspbian stretch lite tout juste installée. On lit:
```
CREATE OR REPLACE TABLE users
(
	id INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	admin BOOLEAN NOT NULL DEFAULT FALSE,
	transfer BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY (id),
	UNIQUE (email)
);
```

En cherchant un peu, j'ai trouvé qu'un caractère UTF8mb4 pèse 4 octets, pour une limite de 767 dans les bases InnodB pour les clés "unique". Or 4*255>767.
Donc en passant le maximum à 191, la base est créée sans erreur.

Voici la ligne modifiée:

```
CREATE OR REPLACE TABLE users
(
	id INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(191) NOT NULL,
	password VARCHAR(255) NOT NULL,
	admin BOOLEAN NOT NULL DEFAULT FALSE,
	transfer BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY (id),
	UNIQUE (email)

);
```

Je ne sais pas si il y a une raison qui m'échappe pour mettre une limite à 255 pour des adresses mail. En tout cas, la base s'installe avec ces valeurs.

Voilà, 

J'espère avoir fait avancer un peu les choses.

Au plaisir,

**Comment by RaspbianFrance** [comment]
Je fix tout de suite.
